config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    collection  do
      get 'search', to: 'rooms#search'
    end
  end
  resources :reserves
  devise_for :users
  resources :rooms
  get 'accounts/show'
  resources :posts
  root "posts#index"
  resources :users
  resource :account, only: [:edit, :update, :show]
  get '/account', to: 'accounts#show'
  get '/users', to: 'users#show'
  get '/rooms', to: 'rooms#new'
  post '/rooms', to: 'rooms#update'
  get '/reserves/confirm', to: 'reserves#confirm', as: 'confirm_reserve'
  post '/reserves/confirm', to: 'reserves#confirm'
  get '/reserves/confirm', to: 'reserves#index'
  get '/rooms/search', to: 'rooms#search'
  
  resources :reserves, only: [:index, :new, :create, :show] do
    collection do
      post 'confirm'
    end
  end
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :check_in, presence: { message: "チェックイン日を入力してください" }
  validates :check_out, presence: { message: "チェックアウト日を入力してください" }
  validate :check_out_after_check_in
  validates :number_of_people, presence: true, numericality: { only_integer: true, greater_than: 0 }
 
  def total_days
    (check_out_in - check_in).to_i
  end
  def total_price
    room = Room.find(room_id)
    total_day * number_of_people.to_i *  @room.price.to_i
  end
  validate :check_out_after_check_in
  def check_out_after_check_in
    if check_in.present? && check_out.present? && check_out <= check_in
      errors.add(:check_out, "はチェックイン日より後の日付にしてください")
    end
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  def index
    @reserves = Reserve.all
    @user = current_user
    @reserve = @user.rooms
  end

  def new
    @room = Room.find(params[:room_id])
    @reserve = @room.reserves.new
    @reserve.user_id = current_user.id 
  end

  def create
    @reserve = Reserve.new(reserve_params)
    @room = Room.find(params[:reserve][:room_id])
    @reserve.room_id = @room.id
    if @reserve.save
      redirect_to @reserve, notice: 'Room was successfully created.'
    else
      render "rooms/show"
    end
  end

  def update
    @reserve = Reserve.new(reserve_params)
  end

  def show
    @reserves = Reserve.all

    if @reserve.nil?
      flash[:error] = '予約情報が見つかりませんでした。'
      redirect_to root_path and return
    end

    @room = @reserve.room
    if @room.nil?
      flash[:error] = '部屋情報が見つかりませんでした。'
      redirect_to root_path and return
    end
  end

  def edit
    @reserve = Reserve.find(params[:id])
    @room = @reserve.room
  end

  def confirm
    @reserve = Reserve.new(reserve_params)
    @room = Room.find(params[:reserve][:room_id])
    @user_id = current_user.id
    @check_in = @reserve.check_in
    @check_out = @reserve.check_out

    if @reserve.check_in.nil?
      redirect_to @room, alert: "開始日を入力してください"
      return
    end
    
    if @reserve.check_out.nil?
      redirect_to @room, alert: "終了日を入力してください"
      return
    end

    if @reserve.check_out < @reserve.check_in
      redirect_to @room, alert: "終了日は開始日以降の日付にしてください"
      return
    end

    if @reserve.number_of_people.nil?
      redirect_to @room, alert: "正しい人数を入力してください"
      return
    end
    
    @total_day = (@check_out - @check_in).to_i
    @number_of_people = @reserve.number_of_people
    @total_price = @room.price.to_i * @total_day * @reserve.number_of_people.to_i
  end

  private

  def reserve_params
    params.require(:reserve).permit(:check_in, :check_out, :number_of_people, :room_id, :user_id)
  end
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_form.html.erb
<%= form_with(model: @reserve) do |form| %>
  <% if @reserve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserve.errors.count, "error") %> prohibited this reserve from being saved:</h2>

      <ul>
        <% @reserve.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
  <div class="field">
    <%= form.label :check_in %>
    <%= form.date_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.date_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.number_field :people %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reserves/confirm.html.erb
<%= form_with model: @reserve ,url: reserves_path do |f| %>

  <h1>予約確認ページ</h1>
  <table>
    <tr>
      <td>チェックイン日:</td>
      <td><%= @reserve.check_in %></td>
    </tr>
    <tr>
      <td>チェックアウト日:</td>
      <td><%= @reserve.check_out %></td>
    </tr>
    <tr>
      <td>宿泊日数:</td>
      <td><%= @total_day %>日</td>
    </tr>
    <tr>
      <td>人数:</td>
      <td><%= @reserve.number_of_people %></td>
    </tr>
    <tr>
      <td>支払い金額:</td>
      <td><%= @total_price %>円</td>
    </tr>
    <tr>
      <td>金額:</td>
      <!-- 金額の表示方法についての情報が不足しているため、具体的なコードを記載することができません -->
    </tr>
  </table>
  <%= f.hidden_field :check_in, value: @reserve.check_in %>
  <%= f.hidden_field :check_out, value: @reserve.check_out %>
  <%= f.hidden_field :number_of_people, value: @reserve.number_of_people %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.submit "予約する" %>
<% end %>

app/views/reserves/edit.html.erb
<div>
  <%= image_tag "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png" %>
</div>
<div>
  <h1 class="hotel-name">
    <%= @room.name %>
  </h1>
</div>
<div class="introduction">
  <%= @room.introduction %>
</div>
<div class="price">
  宿泊料金： <%= @room.price %>円/日
</div>
<%= notice %>
<%= alert %>
<%= form_with model: @reserve, url: confirm_reserve_path, method: :post do |f| %>
<%= render 'layouts/error_messages', model: @reserve %>
  <table>
    <tr>
      <th><%= f.label :check_in, "チェックイン" %></th>
      <td><%= f.date_field :check_in %></td>
    </tr>

    <tr>
      <th><%= f.label :check_out, "チェックアウト" %></th>
      <td><%= f.date_field :check_out %></td>
    </tr>

    <tr>
      <th><%= f.label :number_of_people, "人数" %></th>
      <td><%= f.text_field :number_of_people %></td>
    </tr>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
  </table>

  <%= f.submit "登録する" %>
<% end %>

<%= link_to '戻る', rooms_path, class: "back-link" %>

app/views/reserves/index.html.erb
<h3>予約済み施設一覧</h3>

<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>施設詳細</th>
      <th>金額</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
    </tr>
  </thead>
  <tbody>
    <% @reserves.each do |reserve| %>
      <tr>
        <td><%= image_tag "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png", width: 200 %></td>
        <td><%= Room.find(reserve.room_id).name %></td>
        <td><%= Room.find(reserve.room_id).introduction %></td>
        <td><%= Room.find(reserve.room_id).price * reserve.number_of_people * (reserve.check_out - reserve.check_in).to_i %>円</td>
        <td><%= reserve.check_in.strftime('%Y/%m/%d') %></td>
        <td><%= reserve.check_out.strftime('%Y/%m/%d') %></td>
        <td><%= reserve.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to '編集',   edit_reserf_path(reserve) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reserves/new.html.erb
  <h1>予約確認ページ</h1>
  <table>
    <tr>
      <td>チェックイン日:</td>
      <td><%= @reserve.check_in %></td>
    </tr>
    <tr>
      <td>チェックアウト日:</td>
      <td><%= @reserve.check_out %></td>
    </tr>
    <tr>
      <td>宿泊日数:</td>
      <td><%= @total_day %>日</td>
    </tr>
    <tr>
      <td>人数:</td>
      <td><%= @reserve.number_of_people %></td>
    </tr>
    <tr>
      <td>支払い金額:</td>
      <td><%= @total_price %>円</td>
    </tr>
    <tr>
      <td>金額:</td>
      <!-- 金額の表示方法についての情報が不足しているため、具体的なコードを記載することができません -->
    </tr>
  </table>
  <%= form_with model: @reserve ,url: reserves_path do |f| %>
  <%= f.hidden_field :check_in, value: @reserve.check_in %>
  <%= f.hidden_field :check_out, value: @reserve.check_out %>
  <%= f.hidden_field :number_of_people, value: @reserve.number_of_people %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.submit "予約する" %>
<% end %>

app/views/reserves/show.html.erb
<h3>予約済み施設一覧</h3>

<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>施設詳細</th>
      <th>金額</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
    </tr>
  </thead>
  <tbody>
    <% @reserves.each do |reserve| %>
      <tr>
        <td><%= image_tag "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png", width: 200 %></td>
        <td><%= Room.find(reserve.room_id).name %></td>
        <td><%= Room.find(reserve.room_id).introduction %></td>
        <td><%= Room.find(reserve.room_id).price * reserve.number_of_people * (reserve.check_out - reserve.check_in).to_i %>円</td>
        <td><%= reserve.check_in.strftime('%Y/%m/%d') %></td>
        <td><%= reserve.check_out.strftime('%Y/%m/%d') %></td>
        <td><%= reserve.created_at.strftime('%Y/%m/%d %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>