config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    collection  do
      get 'search', to: 'rooms#search'
    end
  end
  resources :reserves
  devise_for :users
  resources :rooms
  get 'accounts/show'
  resources :posts
  root "posts#index"
  resources :users
  resource :account, only: [:edit, :update, :show]
  get '/account', to: 'accounts#show'
  get '/users', to: 'users#show'
  get '/rooms', to: 'rooms#new'
  post '/rooms', to: 'rooms#update'
  get '/reserves/confirm', to: 'reserves#confirm', as: 'confirm_reserve'
  post '/reserves/confirm', to: 'reserves#confirm'
  get '/reserves/confirm', to: 'reserves#index'
  get '/rooms/search', to: 'rooms#search'
  
  resources :reserves, only: [:index, :new, :create, :show] do
    collection do
      post 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/new_confirm.rb
class NewConfirm < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :reserves
    has_many :rooms 
    def self.ransackable_attributes(auth_object = nil)
        %w[name introduction address created_at updated_at]
      end
    
      def self.ransackable_associations(auth_object = nil)
        %w[reserves rooms]
      end
    
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :check_in, presence: { message: "チェックイン日を入力してください" }
  validates :check_out, presence: { message: "チェックアウト日を入力してください" }
  validate :check_out_after_check_in
  validates :number_of_people, presence: true, numericality: { only_integer: true, greater_than: 0 }
 
  def total_days
    (check_out_in - check_in).to_i
  end
  def total_price
    room = Room.find(room_id)
    total_day * number_of_people.to_i *  @room.price.to_i
  end
  validate :check_out_after_check_in
  def check_out_after_check_in
    if check_in.present? && check_out.present? && check_out <= check_in
      errors.add(:check_out, "はチェックイン日より後の日付にしてください")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :reserves
  validates :name , presence: true 
  validates :address , presence: true
  validates :price , presence: true , numericality: { greater_than_or_equal_to: 0 }
  validates :introduction, presence: true 

  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "id", "introduction", "name", "price", "room_image", "updated_at", "user_id","room_id"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["reservations", "user"]
  end

  def self.search(area, keyword)
    rooms = Room.all

    if area.present?
      rooms = rooms.where("address LIKE ?", "%#{area}%")
    end

    if keyword.present?
      rooms = rooms.where("name LIKE ?", "%#{keyword}%")
    end

    rooms
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :reserves
         has_many :rooms
         def self.looks(search, word)
          if search == "perfect_match"
            @user = User.where("name LIKE?", "#{word}")
          elsif search == "forward_match"
            @user = User.where("name LIKE?","#{word}%")
          elsif search == "backward_match"
            @user = User.where("name LIKE?","%#{word}")
          elsif search == "partial_match"
            @user = User.where("name LIKE?","%#{word}%")
          else
            @user = User.all
          end
        end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:room).order("created_at desc")
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @user = current_user
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:name, :email, :password_digest)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @user = current_user
    @rooms = @user.rooms
    @rooms = Room.all
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = current_user.id
    @room = Room.find(params[:id])
    @reserve = Reserve.new
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to rooms_path
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def search
    @results = @q.result(distinct: true)
    @rooms = Room.where(some_condition: true)
  end

  private

  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :avatar, :user_id, :room_id)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
      
    end
    def show
      @user= current_user
     
    end
   
      def edit
      @user = User.find(params[:id])
      render :edit
    end
  
    def update
      @user = User.find(params[:id])
      binding.pry
      if @user.update(user_params)
        redirect_to user_path, notice: 'プロフィールを更新しました'
      else
        render :edit
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :profile, :avatar)
    end
  end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/helpers/new_condirm_helper.rb
module NewCondirmHelper
end

app/helpers/new_confirm_helper.rb
module NewConfirmHelper
end

app/helpers/new_confirms_helper.rb
module NewConfirmsHelper
end

app/helpers/new_confrim_helper.rb
module NewConfrimHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/new_confirms/_form.html.erb
<%= form_with(model: new_confirm) do |form| %>
  <% if new_confirm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_confirm.errors.count, "error") %> prohibited this new_confirm from being saved:</h2>

      <ul>
        <% new_confirm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.text_field :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.text_field :check_out %>
  </div>

  <div class="field">
    <%= form.label :head_count_interger %>
    <%= form.text_field :head_count_interger %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!doctype html>
<html lang="ja">
 
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 
    <title>Hello, world!</title>
</head>
 
<body>
<header>
<% if user_signed_in? %>
  <!-- ユーザーがログインしていた時の処理 -->
<div class="dropdown">
    <a class="dropdown-toggle ml-auto" href="#" id="user-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      名前 <%= current_user.name %>
    </a>
    </a>
<div class="dropdown-menu" aria-labelledby="user-dropdown">
  <%= link_to "プロフィール", user_path(current_user), class: 'dropdown-item' %>
  <%= link_to "施設予約一覧", reserves_path, class: 'dropdown-item' %> 
  <%= link_to "部屋予約一覧", rooms_path, class: 'dropdown-item' %>
  <%= link_to 'アカウント', account_path, class: 'dropdown-item' %>
  <%= link_to '施設新規登録', new_room_path, class: 'dropdown-item' %>
  <div class="dropdown-divider"></div>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
</div>
</div>
</div>
 

<div class = "search_index">
<h4>キーワード検索</h4>          
<%= search_form_for @q, url: search_rooms_path do |f| %>
  <%= f.label :name_or_introduction_cont ,"キーワード" %>
  <%= f.search_field :name_or_introduction_cont %>
  <%= f.submit "検索", class: "search-button" %>
<% end %>
<h4>住所検索</h4>
<%= search_form_for @q, url: search_rooms_path do |f| %>
  <%= f.label :address_cont, '住所' %>
  <%= f.search_field :address_cont %>
  <%= f.submit '検索' %>
<% end %>
</div>

</div>
</div>

<div class = "all_spots">

<div class="item-container">
  <div class="item"> 
    <div class="spot">    
      <span>東京</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/tokyo.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "東京" }) %>
    </div>
  </div>

  <div class="item"> 
    <div class="spot">  
      <span>大阪</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/osaka.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "大阪" }) %>
    </div>
  </div>

  <div class="item"> 
    <div class="spot">
      <span>京都</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/kyoto.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "京都" }) %>
    </div>  
  </div>

  <div class="item"> 
    <div class="spot">
      <span>札幌</span>
      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/sapporo.jpg", size: "100x100"), search_rooms_path(q: { address_cont: "札幌" }) %>
    </div>          
  </div>
</div>
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
<header>
  <%= image_tag "https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" %>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
</header>

<h2> ポテパンキャンプ　宿泊アプリ　</h2>
 <img src="https://rails-02-sample.herokuapp.com/assets/home/cover-lg.jpg" width="1000" alt="画像">
<% end %>
</header>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @post.password_digest %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>編集</h1>
<%= render 'layouts/error_messages', model: @room %>
<%= form_with(model: @room, local: true) do |form| %>

  <div class="field">
    <%= form.label :施設名%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :施設詳細 %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.number_field :price %>
  </div>
  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address %>
  </div>
  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to '戻る', rooms_path %>

app/views/rooms/index.html.erb
<h1>施設一覧</h1>
<table>
  <thead>
    <tr>
      <th>施設画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>宿泊料金（/日）</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
    <tr>
      <td><%= image_tag "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png", width:200%> <br>
      <td><%= link_to room.name, room_path(room) %></td>
      <td><%= room.introduction %></td>
      <td><%= room.price %>円</td>
      <td><%= room.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= link_to '編集', edit_room_path(room) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= search_form_for @q, url: search_rooms_path do |f| %>

  <%= f.label :name_or_introduction_cont ,"キーワード検索" %>
  <%= f.search_field :name_or_introduction_cont %>
  <%= f.submit "探す", class: "search-button" %>
<% end %>

app/views/rooms/new.html.erb
<h1>施設作成</h1>
<%= render 'layouts/error_messages', model: @room %>
<%= form_with(model: @room, local: true) do |form| %>

  <div class="field">
    <%= form.label :施設名%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :施設詳細 %>
    <%= form.text_area :introduction %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.number_field :price %>
  </div>
  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address %>
  </div>
  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>
 <%= form.hidden_field :user_id, value: @user.id %>
 <%= form.hidden_field :room_id, value: @room.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to '戻る', rooms_path %>

app/views/rooms/search.html.erb
<div class = "search" > 
    <h1>検索結果：<%= @results.count %>件</h1>

    <div class = "search_base" >
        <% @results.each do |results| %>
                    <div class = "search_room" >
                        <h1>施設名<%= results.name %></h1>
                        <h4>施設詳細:<%= results.introduction %></h4>
                        <h4>エリア名：<%= results.address %></h4>
                        <h4>金額：<%= results.price %>円</h4>
                        <h4><%= link_to "詳細を見る", room_path(results) %></h4>
                    </div>
            </div>
        <% end %>
    </div>
    <a href="javascript:history.back()">[戻る]</a>
</div>

app/views/rooms/show.html.erb
<div>
  <%= image_tag "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png" %>
</div>
<div>
  <h1 class="hotel-name">
    <%= @room.name %>
  </h1>
</div>
<div class="introduction">
  <%= @room.introduction %>
</div>
<div class="price">
  宿泊料金： <%= @room.price %>円/日
</div>
<%= notice %>
<%= alert %>
<%= form_with model: @reserve, url: confirm_reserve_path, method: :post do |f| %>
<%= render 'layouts/error_messages', model: @reserve %>
  <table>
    <tr>
      <th><%= f.label :check_in, "チェックイン" %></th>
      <td><%= f.date_field :check_in %></td>
    </tr>

    <tr>
      <th><%= f.label :check_out, "チェックアウト" %></th>
      <td><%= f.date_field :check_out %></td>
    </tr>

    <tr>
      <th><%= f.label :number_of_people, "人数" %></th>
      <td><%= f.text_field :number_of_people %></td>
    </tr>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
  </table>

  <%= f.submit "登録する" %>
<% end %>

<%= link_to '戻る', rooms_path, class: "back-link" %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with(model: @user, url: user_path(@user), method: :patch) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :profile %>
    <%= form.text_area :profile, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>

  <%= form.submit "更新", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h2>プロフィール画面</h2>
<h3>アイコン画像<h3>
<%= image_tag "https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" %>
<h1>ユーザー名</h1>
<%= @user.name %>
<h1>自己紹介<h1>
<%= @user.profile  %>

<li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>